package packagebean;
// Generated Jun 29, 2016 12:29:40 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="admins"
)
public class Admins  implements java.io.Serializable {


     private int id;
    
     public String password;

     String username;

    public Admins() {
    }

    public Admins(String username, String password) {
       this.username = username;
       this.password = password;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    

    
    @Column(name="username")
    public String getUsernamename() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    

    String getFirstName() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    String getLastName() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
   


}


