package packagebean;
// Generated Jun 29, 2016 12:29:40 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="students"
)
public class Students  implements java.io.Serializable {


     private int id;
     private String email;
     public String firstname;
     private String lastname;
     private int numberofanswers;
     private int numberofrightanswers;
     public String password;
     private String property;
     public String quiz1;
     public String quiz2;
     public String quiz3;
     public String course1;
     public String course2;
     public String course3;
    public int age;
    public int preliminary_test;
    public String level;
     

    
    public Students() {
    }

    public Students(String email, String firstname, String lastname, int numberofanswers, int numberofrightanswers, String password, String property, String quiz1, String quiz2, String quiz3,String course1,String course2, String course3,int age,int preliminary_test,String level) {
       this.email = email;
       this.firstname = firstname;
       this.lastname = lastname;
       this.numberofanswers = numberofanswers;
       this.numberofrightanswers = numberofrightanswers;
       this.password = password;
       this.property = property;
       this.quiz1="no";
       this.quiz2="no";
       this.quiz3="no";
       this.course1="no";
       this.course2="no";
       this.course3="no";
       this.age = age;
       this.preliminary_test = -1;
       this.level = "unranked";
               
    }

    Students(String email, String firstname, String lastname, int i, int i0, String password, String property, String quiz1, String quiz2, String quiz3, String course1, String course2, String course3) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="firstname")
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname")
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="numberofanswers")
    public int getNumberofanswers() {
        return this.numberofanswers;
    }
    
    public void setNumberofanswers(int numberofanswers) {
        this.numberofanswers = numberofanswers;
    }

    
    @Column(name="numberofrightanswers")
    public int getNumberofrightanswers() {
        return this.numberofrightanswers;
    }
    
    public void setNumberofrightanswers(int numberofrightanswers) {
        this.numberofrightanswers = numberofrightanswers;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="property")
    public String getProperty() {
        return this.email;
    }
    
    public void setProperty(String property) {
        this.property = property;
    }
    
     @Column(name="quiz1")
    public String getQuiz1() {
        return this.quiz1;
    }
    
    public void setQuiz1(String quiz1) {
        this.quiz1 = quiz1;
    }
    
       @Column(name="quiz2")
    public String getQuiz2() {
        return this.quiz2;
    }
    
    public void setQuiz2(String quiz2) {
        this.quiz2 = quiz2;
    }

       @Column(name="quiz3")
    public String getQuiz3() {
        return this.quiz3;
    }
    
    public void setQuiz3(String quiz3) {
        this.quiz3 = quiz3;
    }
    
     @Column(name="course1")
    public String getCourse1() {
        return this.course1;
    }
    
    public void setCourse1(String course1) {
        this.course1 = course1;
    }
    
    @Column(name="course2")
    public String getCourse2() {
        return this.course2;
    }
    
    public void setCourse2(String course2) {
        this.course2 = course2;
    }
    
    @Column(name="course3")
    public String getCourse3() {
        return this.course3;
    }
    
    public void setCourse3(String course3) {
        this.course3 = course3;
    }
    
    
    String getFirstName() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    String getLastName() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
   


}


